# utils/report.py
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
import datetime
import os

def export_report(kpis: dict, filename_prefix="sales_report", save_dir="."):
    """
    Create a PDF report containing the KPIs dictionary.
    Returns the full filename path.
    """
    # Ensure save directory exists
    os.makedirs(save_dir, exist_ok=True)

    # Generate safe timestamped filename
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(save_dir, f"{filename_prefix}_{ts}.pdf")

    try:
        doc = SimpleDocTemplate(filename, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title = Paragraph("Sales Analysis Report", styles['Title'])
        story.append(title)
        story.append(Spacer(1, 12))

        # Timestamp
        ts_text = Paragraph(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal'])
        story.append(ts_text)
        story.append(Spacer(1, 12))

        # KPIs Table
        table_data = [["Metric", "Value"]]
        for k, v in kpis.items():
            table_data.append([k, str(v)])

        t = Table(table_data, colWidths=[200, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#2E86AB")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('BACKGROUND', (0,1), (-1,-1), colors.whitesmoke)
        ]))
        story.append(t)
        story.append(Spacer(1, 24))

        # Footer
        footer = Paragraph("This report was generated by the Sales Analysis Platform.", styles['Italic'])
        story.append(footer)

        # Build PDF
        doc.build(story)
        return filename

    except Exception as e:
        print(f"Error generating PDF report: {e}")
        return None
